---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/enrichment_some_overlap/enrichment_some_overlap.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/279354/articles/437781/master/file/figures/enrichment_some_overlap/enrichment_some_overlap.png"
    folder_url: "/users/279354/articles/437781/master/folder/figures/enrichment_some_overlap"
